[package]
name = "o-sfu-proofs"
description = "Formal proofs for o-sfu subsystems"

authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
o-sfu-protocol = { path = "../../protocol", features = ["verification-models"] }
o-sfu-rfc = { path = "../../rfc" }
o-sfu-router = { path = "../../router" }
serde_json.workspace = true

[lints]
workspace = true
