[package]
name = "o-sfu-proofs"
description = "Formal proofs for o-sfu subsystems"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version = "1.93"
version.workspace = true

[dependencies]
o-sfu-rfc.workspace = true

[lints]
workspace = true
