[package]
name = "o-sfu-rfc"
description = "RFC-backed protocol constants and literals for o-sfu"
authors.workspace = true
edition.workspace = true
rust-version = "1.93"
version.workspace = true

[dependencies]
base64.workspace = true
serde.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
