[package]
name = "o-sfu-rfc"
description = "RFC-backed protocol constants and literals for o-sfu"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
