# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
      - "AI"
      - "lang-rust"

  - package-ecosystem: "cargo"
    directory: "/router"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
      - "AI"
      - "lang-rust"

  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
      - "AI"
      - "lang-rust"

  - package-ecosystem: "cargo"
    directory: "/telemetry"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
      - "AI"
      - "lang-rust"

  - package-ecosystem: "cargo"
    directory: "/protocol"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
      - "AI"
      - "lang-rust"

  - package-ecosystem: "cargo"
    directory: "/tests"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "cargo"
      - "AI"
      - "lang-rust"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
      - "AI"
      - "lang-js"
