[package]
name = "o-sfu-router"
description = "Router core for o-sfu"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version = "1.93"
version.workspace = true

[features]
test-support = []

[lints]
workspace = true

[dependencies]
o-sfu-rfc.workspace = true
