[workspace]
members = ["rfc", "router"]
resolver = "3"

[workspace.package]
authors = ["ThanhDodeurOdoo"]
edition = "2024"
rust-version = "1.92"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
axum = { version = "0.8", features = ["ws"] }
base64 = "0.22"
crossbeam-channel = "0.5"
flatbuffers = "25.12"
futures-util = "0.3"
hmac = "0.13"
o-sfu-rfc = { path = "rfc" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11.0"
str0m = { version = "0.18", default-features = false, features = ["aws-lc-rs"] }
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1.50", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-tungstenite = "0.29"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.18", features = ["v4"] }

[workspace.lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(kani)",
    "cfg(rust_analyzer)",
] }
unsafe_code = "deny"

[workspace.lints.clippy] # https://rust-lang.github.io/rust-clippy/
correctness = { level = "deny", priority = -1 }
expect_used = { level = "deny", priority = -1 }
indexing_slicing = { level = "deny", priority = -1 }
panic = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
unwrap_used = { level = "deny", priority = -1 }

# groups
complexity = "warn"
pedantic = "warn"
perf = "warn"
style = "warn"

absolute_paths = "warn"
allow_attributes_without_reason = "warn"
as_conversions = "warn"
as_ptr_cast_mut = "warn"
as_underscore = "warn"
assigning_clones = "warn"
clone_on_ref_ptr = "warn"
cognitive_complexity = "warn"
dbg_macro = "warn"
disallowed_script_idents = "warn"
empty_drop = "warn"
exit = "warn"
map_err_ignore = "warn"
mem_forget = "warn"
non_ascii_literal = "warn"
print_stderr = "warn"
print_stdout = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
unused_result_ok = "warn"
wildcard_dependencies = "warn"

# nursery as of rust 1.92 https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html?groups=nursery
needless_pass_by_ref_mut = "warn"
nonstandard_macro_braces = "warn"
option_if_let_else = "warn"
redundant_clone = "warn"
significant_drop_tightening = "warn"
single_option_map = "warn"
trait_duplication_in_bounds = "warn"
type_repetition_in_bounds = "warn"
uninhabited_references = "warn"
unnecessary_struct_initialization = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
while_float = "warn"

[package]
description = "o-sfu"
name = "o-sfu"

authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
futures-util.workspace = true
hmac.workspace = true
o-sfu-rfc.workspace = true
o-sfu-router = { path = "router" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
str0m.workspace = true
time.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }
tower = { version = "0.5", features = ["util"] }
