[package]
name = "o-sfu-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
o-sfu = { path = ".." }
o-sfu-protocol = { path = "../protocol" }
serde_json = "1.0"

[[bin]]
name = "protocol_decode"
path = "fuzz_targets/protocol_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "http_disconnect_auth"
path = "fuzz_targets/http_disconnect_auth.rs"
test = false
doc = false
bench = false

[[bin]]
name = "protocol_sequence"
path = "fuzz_targets/protocol_sequence.rs"
test = false
doc = false
bench = false
