[package]
description = "o-sfu media core"
name = "o-sfu-core"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
fuzzing = []
internal-benchmarks = []
testing-transport = ["o-sfu-router/test-support"]
worker-benchmarks = ["internal-benchmarks"]

[dependencies]
bitflags = "2.6"
futures-util.workspace = true
o-sfu-rfc.workspace = true
o-sfu-model.workspace = true
o-sfu-router.workspace = true
o-sfu-telemetry.workspace = true
serde.workspace = true
serde_json.workspace = true
str0m.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid = { version = "1.18", features = ["v4"] }

[lints]
workspace = true

[dev-dependencies]
o-sfu-telemetry = { workspace = true, features = ["test-support"] }
o-sfu-router = { workspace = true, features = ["test-support"] }
